### PR TITLE
Release 5.0.1

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by ekohl** [comment]
Could you submit a PR to https://github.com/voxpupuli/puppet-example to see if this would pass?

**Comment by bastelfreak** [comment]
https://github.com/voxpupuli/puppet-example/pull/13 looks good

**Review by ekohl — APPROVED** [review]
We should document that Puppet 5 (and older) now really is unsupported.

**Comment by bastelfreak** [comment]
I added a note about dropped puppet 5 / ruby 2.4 support

**Pull request merged**
