### PR TITLE
Pin rubocop to version 0.37.0

### PR DESCRIPTION
**Pull request by dhoppe**
This should solve the error message ```unrecognized cop Style/TrailingCommaInArguments``` of issue #74.

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
It might be worth doing a modulesync of some of the modules in managed_modules.yml to see if this version introduces some gotchas

**Comment by dhoppe** [comment]
@juniorsysadmin In this case I have to pin Ruby to version 2.1.7, because 2.1.8 broke every bulid at Travis CI in the last few days.

**Comment by juniorsysadmin** [comment]
Ah right, I'm okay with merging this then.

**Comment by dhoppe** [comment]
@juniorsysadmin Then you should push the magic button.

**Pull request merged**
