### PR TITLE
Update puppet-strings to 2.0 release

### PR DESCRIPTION
**Pull request by logicminds**
This updates the puppet-strings gem to version 2.0

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @logicminds. can you please test this PR on a module with a REFERENCE.md and regenerate it? We need to ensure that the updates to this repository work on our modules.

**Comment by logicminds** [comment]
https://github.com/voxpupuli/puppet-extlib/pull/129/files/cad899ba45088389208a714e6134f408ef046c0e#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R69

I ended up  using the following strings command instead because I couldn't figure out how to pass additional paths to the rake command.  But this is a extlib requirement.

`bundle exec puppet strings generate --format=markdown lib/puppet/functions/extlib/*.rb functions/*.pp`

**Comment by ekohl** [comment]
How about we ensure the latest and start relying on `rake strings:generate:reference` that was introduced in the latest version?

**Comment by ekohl** [comment]
I'm updating https://github.com/voxpupuli/modulesync_config/pull/543 to rely on that as well. Taking it further from there.

**Pull request closed without merging**
