### PR TITLE
Add puppet-logstash

### PR DESCRIPTION
**Pull request by h-haaks**
@bastelfreak is it possible to get this into the 5.4.0 release?
See https://github.com/voxpupuli/puppet-logstash/pull/418

### CODE REVIEW

**Comment by bastelfreak** [comment]
Interesting that it was missing

**Review by bastelfreak — APPROVED** [review]

**Comment by bastelfreak** [comment]
@h-haaks this repo requires gpg-signed git commits. Is that something you can configure on your end? GitHub has docs about it: https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by h-haaks** [comment]
I'll see what I can do.

**Comment by h-haaks** [comment]
Commit signed:)
Could you please merge @bastelfreak ?

**Pull request merged**
