### PR TITLE
(GH-226) Add CHANGELOG

### LINKED ISSUE #226: changelog
This repo needs a changelog

### PR DESCRIPTION
**Pull request by ghoneycutt**
This patch also adds CONTRIBUTING.md with instructions on how to
generate the CHANGELOG.

Fixes #226

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @ghoneycutt, thanks for the PR. Do you have a gpg key to sign the commit available? At the moment commits to this repo need to be signed.

**Comment by ghoneycutt** [comment]
nope.. good thing to add to the contributors doc :)

**Comment by ghoneycutt** [comment]
@bastelfreak This commit is now verified.

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
