### PR TITLE
puppet6 is released, use it with acceptance tests

### PR DESCRIPTION
**Pull request by Dan33l**
Now puppet6 is realsed it is better to not use nightly as default.

### CODE REVIEW

**Comment by bastelfreak** [comment]
Should we instead add another travis slot for this? @dhollinger recommended this. We could test on puppet6 + puppet6-nightlies to catch issues early.

**Comment by Dan33l** [comment]
Yes i agree. I probably misunderstood a resource limit about CI slots.
Done

**Comment by ekohl** [comment]
IMHO the nightly testing could be good if we have cron runs of modules but AFAIK we don't do so now. That'd mean we have to get a PR in and just get lucky to see something break.

**Comment by bastelfreak** [comment]
@ekohl I would like to have that, but who has time for that to configure it :(. I think nevertheless we should test the nightlies and afterwards try to enable the crons in travis

**Pull request merged**
