### PR TITLE
Manage corosync

### PR DESCRIPTION
**Pull request by roidelapluie**

### CODE REVIEW

**Comment by jyaworski** [comment]
Can you link to the modulesync PR?

**Comment by roidelapluie** [comment]
Is there one?

**Comment by jyaworski** [comment]
For example, whenever I added this to puppet-rundeck I opened https://github.com/voxpupuli/puppet-rundeck/pull/134

**Comment by juniorsysadmin** [comment]
Please don't merge until *after* the module has been synced.

**Pull request closed without merging**
