### PR TITLE
update ruby patch releases

### PR DESCRIPTION
**Pull request by bastelfreak**
this got tested at
https://travis-ci.org/bastelfreak/puppet-mirror/jobs/156647703

### CODE REVIEW

**Comment by igalic** [comment]
i'm confused.
can you elaborate (in your commit message) why rvm isn't handling this itself?
why do we have to manually bump versions??

**Comment by bastelfreak** [comment]
RVM does not provide all patch releases by itself. Using `2.1` will use the latest availavle 2.1.X release that rvm serves. Using `2.1.9` will use the this specific version. RVM uses http://rubies.travis-ci.org/ as source if it doesn't find the version on rvm.org

**Comment by bastelfreak** [comment]
We already had to do that for ruby2.3.1

**Comment by igalic** [comment]
this sucks :(

**Pull request merged**
