### PR TITLE
Add puppet-lint-anchor-check

### PR DESCRIPTION
**Pull request by alexjfisher**
Somehow forgot about adding this 2 years ago!

### CODE REVIEW

**Comment by ekohl** [comment]
Needs a rebase now. I do wonder if there's really no use for anchors anymore but I agree that in most cases it's not relevant anymore. Do you have any idea how many modules would be affected by this?

**Comment by alexjfisher** [comment]
One module where it might still be needed, or at least difficult to refactor is puppet/selinux.  In the majority of cases `contain` should be used instead and for the others we identify, there's always the option to disable the check with a control-comment.

**Comment by ekohl** [comment]
:+1: to using the control-comment.

**Comment by bastelfreak** [comment]
@alexjfisher I cannot push to your branch. Please rebase.

**Pull request merged**
