### PR TITLE
Add puppet-openvmtools to managed_modules

### PR DESCRIPTION
**Pull request by cdenneen**
@razorsedge

### CODE REVIEW

**Comment by cdenneen** [comment]
@alexjfisher @bastelfreak I'm no sure this travis is related?

**Comment by cdenneen** [comment]
only failure is Ruby 1.8.7 which probably should be removed from testing anyway

**Comment by dhoppe** [comment]
@cdenneen Please take a look at our website. It contains information about how to migrate a module to Vox Pupuli. 
* https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli

At the moment this module does not belong to our GitHub namespace, which also explains the following error message:
```
Git::GitExecuteError: git  clone '--' 'https://github.com/voxpupuli/puppet-openvmtools.git' 'modules/puppet-openvmtools'  2>&1:Cloning into 'modules/puppet-openvmtools'...
remote: Invalid username or password.
```

**Comment by ekohl** [comment]
Is there the intention to migrate this module or shall we close this?

**Comment by cdenneen** [comment]
@razorsedge hasn’t responded but yes the attempt is to migrate this module

**Comment by alexjfisher** [comment]
migrate or just fork if there's no response?

**Comment by alexjfisher** [comment]
https://github.com/razorsedge/puppet-openvmtools/issues/12 has been opened with no response.  Still... I really prefer forking a module only as a last resort.  @cdenneen Have you tried emailing Mike?  Contact details on his [website](https://intelligentsysadmin.wordpress.com/gpg-key/).

**Comment by ekohl** [comment]
Has been added via another PR.

**Pull request closed without merging**
