### PR TITLE
bump Puppet from 3.8.5 to 3.8.6

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by jyaworski** [comment]
I kept this at 3.8.5 because there is no 3.8.6 gem on Linux at rubygems.

**Comment by igalic** [comment]
oh??

**Comment by bastelfreak** [comment]
I just checked https://rubygems.org/gems/puppet/versions, there are 3.8.6 deps/rpms and windows gems, but no linux gems. something is strange here

**Comment by rnelson0** [comment]
Why not set it to `~> 3.0`?

**Comment by rnelson0** [comment]
For instance, in my controlrepo: `  gem "puppet", ENV['PUPPET_GEM_VERSION'] || '~> 3.0'` (which IMO is a more readable way to describe this as well).

**Pull request merged**
