### PR TITLE
Add debian 6 to acceptance testing, use puppet boxes

### PR DESCRIPTION
**Pull request by jyaworski**
@rnelson0 @bastelfreak

### CODE REVIEW

**Comment by bastelfreak** [comment]
why adding debian 6? this is EOL since a long long time. even their LTS support is now dropped. We're currently trying to get rid of ruby1.8, testing on debian6 would be a step backwards IMO.

**Comment by jyaworski** [comment]
@bastelfreak Puppet itself is still testing against it (per their vagrant boxes).

**Comment by bastelfreak** [comment]
I know, but still, long term EOL, I am against that. Does anybody else have opinions here? @igalic or @nibalizer?

**Comment by igalic** [comment]
i'm not sure i agree with this…

**Pull request closed without merging**
