### PR TITLE
add pmtignore to exclude strings-docs

### PR DESCRIPTION
**Pull request by bastelfreak**
We need to discuss if we want this or not. In the past we had issues with builds that were too big so we might need to exclude the docs from releases.

### CODE REVIEW

**Comment by rnelson0** [comment]
Docs don't do any good on my puppet master.

**Comment by dhollinger** [comment]
Considering docs can be generated with a rake task, I don't see why we need them pulled from the Forge

**Comment by vinzent** [comment]
Including the reason why it is excluded in the commit message would be nice. So if anybody in 6 months looks at it can see it right away from the git log.

http://chris.beams.io/posts/git-commit/#seven-rules

**Comment by bastelfreak** [comment]
good point, updated the commit message.

**Pull request merged**
