### PR TITLE
This cop is useless for Puppet

### PR DESCRIPTION
**Pull request by jyaworski**
@rnelson0 @bastelfreak

### CODE REVIEW

**Comment by rnelson0** [comment]
Definitely not helpful. Was this biting us, though? I had not seen failures for it before.

**Comment by jyaworski** [comment]
@rnelson0 yes, it was in the test PR I had with collectd. The first line of every file would fail due to the format.

**Comment by rnelson0** [comment]
Is that new with the latest version of rubocop or something?

**Comment by jyaworski** [comment]
@rnelson0 rubocop-rspec.

**Pull request merged**
