### PR TITLE
Release 7.5.0

### PR DESCRIPTION
**Pull request by h-haaks**

### CODE REVIEW

**Comment by h-haaks** [comment]
Not really sure if this is needed right now.
I'm planning to start implementing `with` in module repos, and if someone runs msync with the 7.4.0 tag it will fail.

**Review by bastelfreak — APPROVED** [review]

**Comment by h-haaks** [comment]
@bastelfreak is this repo manually taged? Don't see anything in gha workflows.

**Comment by bastelfreak** [comment]
yes. merge the PR, create a signed tag and push it

**Comment by h-haaks** [comment]
lightweight or annotated tag?

**Pull request merged**
