### PR TITLE
Remove some redundant requires from Rakefile

### PR DESCRIPTION
**Pull request by alexharv074**
All of these are in puppetlabs_spec_helper/rake_tasks.rb

### CODE REVIEW

**Comment by rnelson0** [comment]
For lack of ability to test this myself right now, got a link to a module with this trimmed file that tests properly?

**Comment by alexharv074** [comment]
How about `lib/puppetlabs_spec_helper/rake_tasks.rb` at [https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/rake_tasks.rb#L6-L11](lines 6-11), [376](https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/rake_tasks.rb#L376) and [393](https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/rake_tasks.rb#L393).

I tested by removing all those lines and confirming that I had 23 rake tasks with or without them in `rake -T`.  I don't know of a module that has this config, other than one I'm not quite ready to push.  Will this do?

**Comment by alexharv074** [comment]
The latest version of `lib/puppetlabs_spec_helper/rake_tasks.rb` at [line 3](https://github.com/puppetlabs/puppetlabs_spec_helper/blob/master/lib/puppetlabs_spec_helper/rake_tasks.rb#L3) also requires rubocop, but seems like that hasn't been released unfortunately.

**Comment by bastelfreak** [comment]
I just tested this on puppet-zabbix, I get the same amount of rake tasks after applying your patch (42).

**Pull request merged**
