### PR TITLE
Issue  #17 Lock rubocop version to 0.33.0

### PR DESCRIPTION
**Pull request by mkrakowitzer**

### CODE REVIEW

**Comment by jyaworski** [comment]
What is the reasoning behind this? So the cops don't change?

**Comment by juniorsysadmin** [comment]
@jyaworski It definitely should be locked, considering rate of development and the new cops that are added, version 0.33.0 is as good as any. @mkrakowitzer You've got merge conflicts.

**Comment by juniorsysadmin** [comment]
#17

**Comment by jyaworski** [comment]
I am very much a fan of this now.

**Comment by bastelfreak** [comment]
pinned in [PR59](https://github.com/voxpupuli/modulesync_config/pull/59)

**Pull request closed without merging**
