### PR TITLE
Add support for code coverage

### PR DESCRIPTION
**Pull request by dhoppe**
Please merge. This will produce coverage reports, to make sure that we have for almost everything a RSpec check.

### CODE REVIEW

**Comment by jyaworski** [comment]
Tests fail?

**Comment by dhoppe** [comment]
I am pretty sure this is caused by PR #65 and Rubocop 0.35.0, because the error message is complaining about an unrecognized cop ```Style/TrailingCommaInArguments```.

Since we are using a different parameter at [modulesync](https://github.com/voxpupuli/modulesync_config/blob/master/.rubocop.yml#L14) and [moduleroot](https://github.com/voxpupuli/modulesync_config/blob/master/moduleroot/.rubocop.yml#L39), I recommend to use ```Style/TrailingComma``` or upgrading to Rubocop 0.37.0.

Both solutions solved the issue during local tests.

**Comment by juniorsysadmin** [comment]
> I recommend to use Style/TrailingComma or upgrading to Rubocop 0.37.0.

Can we do this in a separate PR then, before merging this?

**Comment by juniorsysadmin** [comment]
On an unrelated note, I don't think it's a good idea to create branches on the voxpupuli namespace rather than your own one, unless you intend that others make changes directly to the branch or you want others to finish the PR off.

**Comment by dhoppe** [comment]
@juniorsysadmin Alright. Just take a look at #75.

**Comment by dhoppe** [comment]
@juniorsysadmin Please merge this PR too.

**Comment by igalic** [comment]
oooh! i got excited for a second thinking you added https://github.com/tushartushar/Puppeteer

**Comment by jyaworski** [comment]
I think I'll look at implementing Puppeteer....

**Pull request merged**
