### PR TITLE
Rubocop again

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by bastelfreak** [comment]
yes. I merged the other PR and resolved the merge commits via the UI. github created the merge commit.

**Comment by vinzent** [comment]
I think if you do a `git rebase upstream/master` on your branch the merge commit will go away .

**Comment by alexjfisher** [comment]
@bastelfreak Still better to rebase though surely?

**Comment by alexjfisher** [comment]
+1 for clean commit history on master if possible

**Comment by bastelfreak** [comment]
okay I did things

**Pull request merged**
