### PR TITLE
Fix github templates

### PR DESCRIPTION
**Pull request by roidelapluie**
- Keep modules simple
- Do not scare people with bullet points
- Stop making pull requests unreadable
- Keep contributing.md

Signed-off-by: Julien Pivotto <roidelapluie@inuits.eu>

### CODE REVIEW

**Comment by roidelapluie** [comment]
scrnshot

CONTRIBUTING.md is already there and less intrusive -- while still visible enough to drag attention

**Comment by bastelfreak** [comment]
I'm against this change. I don't think that many people read the CONTRIBUTING.md before they submit a PR. We maybe should reorganize the templates, but removing them is IMO the wrong way.

**Comment by igalic** [comment]
I absolutely agree with @roidelapluie here: when i created a new pull request after we introduced .github i was *utterly* confused — and i'm not quite a newbie anymore.

The Contributing.md is a good place to stuff general docs. If we want a step-by-step how-to do a good PR, we can write that as a blog post and point newbies to. Same, IMO, for contributing — if someone has a question that's answered there, you can point them to it. I see no reason to modify someone's pr, it's *highly* intrusive!

We've already (mostly) gotten rid of the requirement for squashing / rebasing because github can do that for us by now, so i really see this as a step back.

**Comment by juniorsysadmin** [comment]
+1 The slabs of text have been freaking me out

**Comment by rski** [comment]
I agree on the PR template, because it confused me too.

I disagree on the issue template though. Its points are pretty much things that will be asked anyway by the person who decides to pick up the issue and fix it.

**Comment by roidelapluie** [comment]
Okay, what about this?

**Comment by rski** [comment]
+1

**Comment by igalic** [comment]
:+1:

**Pull request merged**
