### PR TITLE
Ignore Guardfile when doing rubocop checks

### PR DESCRIPTION
**Pull request by juniorsysadmin**
```Style/FileName: The name of this source file (Guardfile) should use snake_case```
Guardfiles are really a personal preference thing and shouldn't be synced or checked

### CODE REVIEW

**Comment by bastelfreak** [comment]
We ship Guardfiles in multiple repos. Should we put them in the .gitignore or should we manage it via modulesync?

**Comment by juniorsysadmin** [comment]
.gitignore . Definitely don't manage via modulesync.

**Comment by bastelfreak** [comment]
Can you update the moduleroot/.gitignore to  also list the Guardfile?

**Comment by juniorsysadmin** [comment]
> Can you update the moduleroot/.gitignore to also list the Guardfile?

Done

**Pull request merged**
