### PR TITLE
add missing encoding to file header

### PR DESCRIPTION
**Pull request by bastelfreak**
Rubocop complaints about this if the cop isn't disabled.

### CODE REVIEW

**Comment by rnelson0** [comment]
...isn't the encoding done on the file, not by comments at the top of it? Does that actually force a non-utf8 file to be utf8?

**Comment by bastelfreak** [comment]
I'm not sure how correct this answer is: http://stackoverflow.com/a/8879359

**Comment by rnelson0** [comment]
http://stackoverflow.com/a/8796676 May be more relevant. Looks like this was only ever needed with Ruby 1.9. I know we are testing with that but since we don't have the cop enabled yet, I think it's premature. Hopefully 1.9 gets out of the picture soon anyway.

**Comment by jyaworski** [comment]
Should we be explicit, though? Like with vim modelines?

**Comment by rnelson0** [comment]
I am generally against pre-mature optimizations :)

**Comment by daenney** [comment]
I'm closing this for now. I don't think it's needed and I haven't seen any issues with it in the past 5 years or so. If it crops up we can deal with it then 😄.

**Pull request closed without merging**
