### PR TITLE
add pdk gem to development group

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by ekohl** [comment]
Should we drop redundant dependencies from our gem file then?

**Comment by bastelfreak** [comment]
Sounds like a good idea, then pdk should not be in the development group, maybe in no group at all.

**Comment by bastelfreak** [comment]
@ekohl I checked https://github.com/puppetlabs/pdk/blob/master/pdk.gemspec#L24-L36, pdk ships less deps than I thought. I think we can just add it to our development group and thats it?

**Comment by ghoneycutt** [comment]
Why would we need pdk to be installed as a gem?

**Comment by ghoneycutt** [comment]
Closing due to inactivity, please feel free to re-open.

**Pull request closed without merging**
